### PR TITLE
Work in progress: MacOS support

### PR DESCRIPTION
**Pull request by jbergstroem**
An attempt at supporting `gentoo-bb` "out of the box" (meaning as few dependencies through homebrew or similar as possible). I'm currently using [docker for mac](https://www.docker.com/products/docker#mac).

Will add commits as I go.

### CODE REVIEW

**Comment by jbergstroem** [comment]
1: shasum512 -> shasum -a512
2: bash re-implementation of realpath
3: avoid a gnu sed-ism by using cat/echo

**Comment by edannenberg** [comment]
lgtm :+1:, also glad you are still alive and kicking, long time no see :)

**Comment by jbergstroem** [comment]
Just revisited this. Sans running into musl-related issues it works fine on MacOS for me. If someone could try the changes out locally in other environments that'd be great.

**Comment by edannenberg** [comment]
Tried the changes on my Gentoo box, no issues.

**Comment by jbergstroem** [comment]
Cool! Feel free to merge; should rebase cleanly.

**Pull request merged**
