### PR TITLE
Add option to run nginx in foreground under s6

### PR DESCRIPTION
**Pull request by gdm**

### CODE REVIEW

**Comment by edannenberg** [comment]
Scratched my head a bit why this ever worked so far before I remembered: https://github.com/edannenberg/gentoo-bb/blob/master/dock/gentoobb/images/nginx/etc/nginx/nginx.conf#L1

Unless I'm missing something this PR adds only redundancy?

**Comment by gdm** [comment]
> so people don't have to remember when replacing nginx.conf with their own version.
Yes its exactly the reason, I've used my own nginx.conf and noticed that nginx was trying to restart every second.

**Comment by gdm** [comment]
I've removed daemon option from nginx.conf.

**Comment by gdm** [comment]
> Scratched my head a bit why this ever worked so far

Actually it "works" without this option with a lot of complains from nginx trying to start every second by s6.

**Comment by edannenberg** [comment]
"works" != works. :p Anyways, thanks!

**Pull request merged**
