### PR TITLE
add stage3 download option

### PR DESCRIPTION
**Pull request by azimut**
helps when testing a new stage3 image, not sure if is really needed as a new command on the core though

### CODE REVIEW

**Comment by edannenberg** [comment]
I'm not sure either. :p How is your workflow for that? Don't you just update `STAGE3_BASE` and rebuild which should download the new stage3?

**Comment by azimut** [comment]
For example to try the experimental musl stage3 I had to play around with the values until I got the correct ones.
```
#  cat build.musl.conf  | grep -e STAGE -e URL | grep -v '^#'
ARCH_URL="${ARCH_URL:-${MIRROR}experimental/${ARCH}/musl/}"
STAGE3_BASE="${STAGE3_BASE:-stage3-armv7a_hardfp-musl-hardened}"
STAGE3="${STAGE3:-${STAGE3_BASE}-${DATE}.tar.bz2}"
STAGE3_CONTENTS="${STAGE3_CONTENTS:-${STAGE3}.CONTENTS}"
STAGE3_DIGESTS="${STAGE3_DIGESTS:-${STAGE3}.DIGESTS}"
PORTAGE_URL="${PORTAGE_URL:-${MIRROR}snapshots/}"
```
That is before I started building a new namespace for it. I just wanted to download the stage3 later I would worry about the namespace. Also I use it along with "trickle" (https://wiki.archlinux.org/index.php/Trickle) to limit the download speed.

But all this might be just because I don't have a lot of download bandwith here. So no problem if isn't merge.

**Comment by edannenberg** [comment]
I see, maybe we should look into improving picking a stage3 then. A section in the documentation would probably do the trick, or maybe scrape distfiles.gentoo.org if we want to get fancy.

**Comment by azimut** [comment]
Kudos for the musl experimental support. Now I think about it I could probably just "source" things with a wrapper to achieve something similar to this pull request without maintaining a fork myself. I will close this for now.

**Comment by edannenberg** [comment]
Thanks. For selecting a stage3 I would like to have a command like `build.sh conf ns/mybuilder`. Then maybe have a simple 2-3 step wizard (or maybe some workflow like `èselect`?) to first select `autobuild` or `experimental` and then list possible stage3 files for the prev. selection and output some copy/pasta text for build.conf once a stage3 is picked and/or update build.conf. Adding an option like `docker images -q` where it would only output the complete stage3 url for all configured base builders would be a low hanging fruit at this point. Should help your `trickle` use case and due to the recent changes we need this kind of functionality anyways for `build.sh update` now.

ps: I noticed your local git email is configured as `you@example.com`, see: https://github.com/edannenberg/gentoo-bb/commit/ff00db813edada2fe9128702e8a1b9d8191035e1 Might want to fix that if you want github to link your commits to your account.

**Pull request closed without merging**
